package srun

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// The vectors come from the frozen baseline Python, regenerated by
// .codex/go-loop/tools/gen_protocol_vectors.py. They prove the Go and the
// shipped implementation agree byte for byte.
//
// On their own that proves only agreement. The independent bases are in the
// other files here: the standard Base64 alphabet against encoding/base64, RFC
// 2202 and RFC 3174 digest vectors, and an XXTEA decrypt that has to recover
// the plaintext.
type protocolVectors struct {
	BaselineCommit  string `json:"baseline_commit"`
	OracleSHA256    string `json:"oracle_sha256"`
	DefaultAlphabet string `json:"default_alphabet"`
	PadChar         string `json:"pad_char"`
	Vectors         struct {
		Info []struct {
			Name     string `json:"name"`
			Username string `json:"username"`
			Password string `json:"password"`
			IP       string `json:"ip"`
			ACID     string `json:"ac_id"`
			Enc      string `json:"enc"`
			Info     string `json:"info"`
			InfoHex  string `json:"info_hex"`
		} `json:"info"`
		Xencode []struct {
			Name   string `json:"name"`
			MsgHex string `json:"msg_hex"`
			KeyHex string `json:"key_hex"`
			OutHex string `json:"out_hex"`
		} `json:"xencode"`
		Base64 []struct {
			Name     string `json:"name"`
			InputHex string `json:"input_hex"`
			SRun     string `json:"srun_alphabet"`
			Standard string `json:"standard_alphabet"`
		} `json:"base64"`
		HMACMD5 []struct {
			Name     string `json:"name"`
			Password string `json:"password"`
			Token    string `json:"token"`
			HMD5     string `json:"hmd5"`
		} `json:"hmac_md5"`
		SHA1 []struct {
			Name  string `json:"name"`
			Input string `json:"input"`
			SHA1  string `json:"sha1"`
		} `json:"sha1"`
		Composite []struct {
			Name          string `json:"name"`
			Username      string `json:"username"`
			Password      string `json:"password"`
			IP            string `json:"ip"`
			ACID          string `json:"ac_id"`
			Enc           string `json:"enc"`
			N             string `json:"n"`
			LoginType     string `json:"type"`
			Token         string `json:"token"`
			InfoPrefix    string `json:"info_prefix"`
			InfoJSON      string `json:"info_json"`
			EncryptedInfo string `json:"encrypted_info"`
			HMD5          string `json:"hmd5"`
			ChkStr        string `json:"chkstr"`
			Chksum        string `json:"chksum"`
			WirePassword  string `json:"wire_password"`
		} `json:"composite"`
		LogoutSign []struct {
			Name        string `json:"name"`
			TimeSeconds int64  `json:"time_seconds"`
			Username    string `json:"username"`
			IP          string `json:"ip"`
			Unbind      string `json:"unbind"`
			SignInput   string `json:"sign_input"`
			Sign        string `json:"sign"`
		} `json:"logout_sign"`
	} `json:"vectors"`
}

func loadVectors(t *testing.T) protocolVectors {
	t.Helper()
	data, err := os.ReadFile("../../../testdata/protocol/srun-vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var vectors protocolVectors
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	return vectors
}

func mustHex(t *testing.T, value string) []byte {
	t.Helper()
	decoded, err := hex.DecodeString(value)
	if err != nil {
		t.Fatalf("bad hex %q: %v", value, err)
	}
	return decoded
}

// The alphabet is part of the vectors: generating them against one table and
// encoding with another would make every Base64 comparison meaningless.
func TestVectorsWereGeneratedForThisAlphabet(t *testing.T) {
	vectors := loadVectors(t)
	if vectors.DefaultAlphabet != DefaultAlphabetTable {
		t.Fatalf("vectors use a different default alphabet:\n got %q\nwant %q",
			vectors.DefaultAlphabet, DefaultAlphabetTable)
	}
	if vectors.PadChar != string(PadChar) {
		t.Fatalf("pad char = %q, want %q", vectors.PadChar, string(PadChar))
	}
	if vectors.OracleSHA256 == "" || vectors.BaselineCommit == "" {
		t.Fatal("the vectors do not record which oracle produced them")
	}
}

// T01 -- the info object, byte for byte.
func TestInfoMatchesTheBaselineBytes(t *testing.T) {
	vectors := loadVectors(t)
	if len(vectors.Vectors.Info) == 0 {
		t.Fatal("no info vectors")
	}

	for _, vector := range vectors.Vectors.Info {
		t.Run(vector.Name, func(t *testing.T) {
			produced, err := EncodeInfo(Info{
				Username: vector.Username, Password: vector.Password,
				IP: vector.IP, ACID: vector.ACID, EncVer: vector.Enc,
			})
			if err != nil {
				t.Fatalf("EncodeInfo: %v", err)
			}
			if produced != vector.Info {
				t.Fatalf("info mismatch\n got %s\nwant %s", produced, vector.Info)
			}
			if got := hex.EncodeToString([]byte(produced)); got != vector.InfoHex {
				t.Fatalf("bytes mismatch\n got %s\nwant %s", got, vector.InfoHex)
			}
		})
	}
}

// T02 -- xencode, including the empty message and short keys.
func TestXencodeMatchesTheBaselineBytes(t *testing.T) {
	vectors := loadVectors(t)
	if len(vectors.Vectors.Xencode) == 0 {
		t.Fatal("no xencode vectors")
	}

	for _, vector := range vectors.Vectors.Xencode {
		t.Run(vector.Name, func(t *testing.T) {
			produced := Xencode(mustHex(t, vector.MsgHex), mustHex(t, vector.KeyHex))
			if got := hex.EncodeToString(produced); got != vector.OutHex {
				t.Fatalf("xencode mismatch\n got %s\nwant %s", got, vector.OutHex)
			}
		})
	}
}

// T03 -- the custom alphabet and, in the same file, the standard one.
func TestBase64MatchesTheBaselineBytes(t *testing.T) {
	vectors := loadVectors(t)
	standard, err := NewAlphabet(StandardAlphabetTable)
	if err != nil {
		t.Fatalf("standard alphabet: %v", err)
	}

	for _, vector := range vectors.Vectors.Base64 {
		t.Run(vector.Name, func(t *testing.T) {
			input := mustHex(t, vector.InputHex)
			if got := DefaultAlphabet.Encode(input); got != vector.SRun {
				t.Errorf("srun alphabet: got %q, want %q", got, vector.SRun)
			}
			if got := standard.Encode(input); got != vector.Standard {
				t.Errorf("standard alphabet: got %q, want %q", got, vector.Standard)
			}
		})
	}
}

func TestDigestsMatchTheBaseline(t *testing.T) {
	vectors := loadVectors(t)

	for _, vector := range vectors.Vectors.HMACMD5 {
		t.Run("hmac/"+vector.Name, func(t *testing.T) {
			if got := HMACMD5Hex(vector.Token, vector.Password); got != vector.HMD5 {
				t.Fatalf("hmd5 = %s, want %s", got, vector.HMD5)
			}
		})
	}
	for _, vector := range vectors.Vectors.SHA1 {
		t.Run("sha1/"+vector.Name, func(t *testing.T) {
			if got := SHA1Hex(vector.Input); got != vector.SHA1 {
				t.Fatalf("sha1 = %s, want %s", got, vector.SHA1)
			}
		})
	}
}

// The whole login byte sequence. This is the vector that would actually have
// caught a wrong translation: every stage feeds the next, so a single wrong
// byte anywhere changes the checksum.
func TestTheWholeLoginSequenceMatchesTheBaseline(t *testing.T) {
	vectors := loadVectors(t)
	if len(vectors.Vectors.Composite) == 0 {
		t.Fatal("no composite vectors")
	}

	for _, vector := range vectors.Vectors.Composite {
		t.Run(vector.Name, func(t *testing.T) {
			infoJSON, err := EncodeInfo(Info{
				Username: vector.Username, Password: vector.Password,
				IP: vector.IP, ACID: vector.ACID, EncVer: vector.Enc,
			})
			if err != nil {
				t.Fatalf("EncodeInfo: %v", err)
			}
			if infoJSON != vector.InfoJSON {
				t.Fatalf("info\n got %s\nwant %s", infoJSON, vector.InfoJSON)
			}

			encrypted := EncryptedInfo(vector.InfoPrefix, infoJSON, vector.Token, DefaultAlphabet)
			if encrypted != vector.EncryptedInfo {
				t.Fatalf("encrypted info\n got %s\nwant %s", encrypted, vector.EncryptedInfo)
			}

			hmd5 := HMACMD5Hex(vector.Token, vector.Password)
			if hmd5 != vector.HMD5 {
				t.Fatalf("hmd5 = %s, want %s", hmd5, vector.HMD5)
			}
			if got := WirePasswordPrefix + hmd5; got != vector.WirePassword {
				t.Fatalf("wire password = %s, want %s", got, vector.WirePassword)
			}

			chkstr := ChecksumInput(vector.Token, vector.Username, hmd5,
				vector.ACID, vector.IP, vector.N, vector.LoginType, encrypted)
			if chkstr != vector.ChkStr {
				t.Fatalf("checksum input\n got %s\nwant %s", chkstr, vector.ChkStr)
			}
			if got := SHA1Hex(chkstr); got != vector.Chksum {
				t.Fatalf("chksum = %s, want %s", got, vector.Chksum)
			}
		})
	}
}

// T06 -- the logout signature.
func TestLogoutSignatureMatchesTheBaseline(t *testing.T) {
	vectors := loadVectors(t)
	if len(vectors.Vectors.LogoutSign) == 0 {
		t.Fatal("no logout vectors")
	}

	for _, vector := range vectors.Vectors.LogoutSign {
		t.Run(vector.Name, func(t *testing.T) {
			if vector.Unbind != LogoutUnbind {
				t.Fatalf("unbind = %q, want %q", vector.Unbind, LogoutUnbind)
			}
			got := LogoutSignInput(vector.TimeSeconds, vector.Username, vector.IP)
			if got != vector.SignInput {
				t.Fatalf("sign input\n got %s\nwant %s", got, vector.SignInput)
			}
			if got := LogoutSign(vector.TimeSeconds, vector.Username, vector.IP); got != vector.Sign {
				t.Fatalf("sign = %s, want %s", got, vector.Sign)
			}
		})
	}
}
